<?php

namespace ContainerR8qGhny;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T8WiuCtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T8WiuCt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.T8WiuCt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'product' => ['privates', '.errored..service_locator.T8WiuCt.App\\Entity\\Products', NULL, 'Cannot autowire service ".service_locator.T8WiuCt": it references class "App\\Entity\\Products" but no such service exists.'],
        ], [
            'product' => 'App\\Entity\\Products',
        ]);
    }
}
