<?php

namespace ContainerR8qGhny;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XYeE5nSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XYeE5nS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XYeE5nS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CategoriesController::list' => ['privates', '.service_locator.gFHHwHB', 'get_ServiceLocator_GFHHwHBService', true],
            'App\\Controller\\MainController::index' => ['privates', '.service_locator.Ksprajg', 'get_ServiceLocator_KsprajgService', true],
            'App\\Controller\\ProductsController::details' => ['privates', '.service_locator.T8WiuCt', 'get_ServiceLocator_T8WiuCtService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.iHDFrIU', 'get_ServiceLocator_IHDFrIUService', true],
            'App\\Controller\\RegistrationController::resendVerif' => ['privates', '.service_locator.NMJPVwl', 'get_ServiceLocator_NMJPVwlService', true],
            'App\\Controller\\RegistrationController::verifyUser' => ['privates', '.service_locator.xyz8YWL', 'get_ServiceLocator_Xyz8YWLService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\CategoriesController:list' => ['privates', '.service_locator.gFHHwHB', 'get_ServiceLocator_GFHHwHBService', true],
            'App\\Controller\\MainController:index' => ['privates', '.service_locator.Ksprajg', 'get_ServiceLocator_KsprajgService', true],
            'App\\Controller\\ProductsController:details' => ['privates', '.service_locator.T8WiuCt', 'get_ServiceLocator_T8WiuCtService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.iHDFrIU', 'get_ServiceLocator_IHDFrIUService', true],
            'App\\Controller\\RegistrationController:resendVerif' => ['privates', '.service_locator.NMJPVwl', 'get_ServiceLocator_NMJPVwlService', true],
            'App\\Controller\\RegistrationController:verifyUser' => ['privates', '.service_locator.xyz8YWL', 'get_ServiceLocator_Xyz8YWLService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\CategoriesController::list' => '?',
            'App\\Controller\\MainController::index' => '?',
            'App\\Controller\\ProductsController::details' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::resendVerif' => '?',
            'App\\Controller\\RegistrationController::verifyUser' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CategoriesController:list' => '?',
            'App\\Controller\\MainController:index' => '?',
            'App\\Controller\\ProductsController:details' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:resendVerif' => '?',
            'App\\Controller\\RegistrationController:verifyUser' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
