<?php

namespace ContainerR8qGhny;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.T8WiuCt.App\Entity\Products' shared service.
     *
     * @return \App\Entity\Products
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.T8WiuCt": it references class "App\\Entity\\Products" but no such service exists.');
    }
}
