<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTXXpSsL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTXXpSsL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTXXpSsL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTXXpSsL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTXXpSsL\App_KernelDevDebugContainer([
    'container.build_hash' => 'TXXpSsL',
    'container.build_id' => '3ea97cee',
    'container.build_time' => 1660675489,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTXXpSsL');
